channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=24.0
- pip:
  - mlflow==2.11.3
  - astunparse==1.6.3
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - dill==0.3.1.1
  - numpy==1.24.4
  - packaging==23.2
  - pandas==1.5.3
  - pathlib==1.0.1
  - pydantic==1.10.14
  - pydot==1.4.2
  - pyyaml==6.0.1
  - requests==2.31.0
  - torch==2.2.1
  - transformers==4.38.2
name: mlflow-env
