channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.0
- pip:
  - mlflow==2.10.2
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - dill==0.3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pydantic==2.5.3
  - pydot==2.0.0
  - pyyaml==6.0.1
  - requests==2.31.0
  - torch==2.2.0
  - transformers==4.37.2
name: mlflow-env
